export const CONNECT_NETWORK = 'CONNECT_NETWORK';
export const DISCONNECT_NETWORK = 'DISCONNECT_NETWORK';

export const PLAY_VIDEO = 'PLAY_NETWORK';
export const PAUSED_VIDEO = 'PAUSED_VIDEO';
export const STOP_VIDEO = 'PLAY_NETWORK';

export const LEVEL_PHONE = 'LEVEL_PHONE';
export const VERTICAL_PHONE = 'VERTICAL_PHONE';

export const SIGNAL_BEACONS = 'SIGNAL_BEAONS';
export const NOT_SIGNAL_BEACONS = 'NOT_SIGNAL_BEACONS';

export const CONNECT_BEACON = 'CONNECT_BEACON';
export const DISCONNECT_BEACON = 'DISCONNECT_BEACON';

export const SCAN_BEACONS = 'SCAN_BEACONS';
export const STOP_SCAN_BEACONS = 'STOP_SCAN_BEACONS';